version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: foo
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: tp4-app-dev
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - ./srv:/srv
