name: tests unitaires

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run tests
        run: pytest TP1/test.py

      # Q7.1: Afficher infos de contexte
      - name: Afficher infos du job
        run: |
          echo "Nom de la branche : ${{ github.ref }}"
          echo "Nom du repo      : ${{ github.repository }}"
          echo "OS de la VM      : ${{ runner.os }}"
          echo "Version de Python: ${{ matrix.python-version }}"

