name: tests unitaires

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installation pytest
        run: pip3 install pytest

      - name: Run tests
        run: pytest TP1/test.py

      - name: Afficher infos du job
        run: |
          echo "Nom de la branche : ${{ github.ref }}"
          echo "Nom du repo      : ${{ github.repository }}"


